- name: cisco_backup_config
  hosts: switches
  gather_facts: true 
  tasks:
  - name: Backup Running Configuration
    cisco.ios.ios_config:
     backup: true
     backup_options:
      dir_path: /home/sysadmin/backup/
