- name: cisco_sh_ver
  hosts: switches
  gather_facts: true 
  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
     commands:
     - show version
     wait_for:
      - result[0] contains FORTINET
