- name: cisco_sh_ver
  hosts: switches
  gather_facts: true 
  tasks:
  - name: run show version on remote devices
    cisco.ios.ios_command:
     commands:
     - show version
     register: output
  - name: print Output
    debug: var=output.stdout_lines
